# baseURL = "https://finto-consenso.hermescenter.org/"
languageCode = "it-IT"
title = "Finto Consenso"
defaultContentLanguage = "it"
enableRobotsTXT = true
canonifyURLs = true

[params]
  description = "Campagna contro il finto consenso digitale: il modello Pay or OK è una violazione dei diritti GDPR. Firma la lettera al Garante, unisciti all’azione collettiva."

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  post = "/:slug/"

[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Il problema"
  url = "/problema"
  weight = 2

  [[menu.main]]
  name = "Diritti violati"
  url = "/diritti-negati"
  weight = 3

  [[menu.main]]
  name = "La lettera"
  url = "/lettera"
  weight = 4

  [[menu.main]]
  name = "Firma"
  url = "/firma"
  weight = 5

  [[menu.main]]
  name = "Azione collettiva"
  url = "/azione"
  weight = 6

  [[menu.main]]
  name = "Privacy"
  url = "/privacy"
  weight = 7

  [[menu.main]]
  name = "Chi siamo"
  url = "/chi"
  weight = 8
